### ISSUE TITLE
The Parsable interface is missing data types

### ISSUE THREAD

**Issue by baywet** [ricardoboss/dart_kiota_abstractions#1]
This is for later, but we're probably missing:
- DateOnly (or equivalent)
- TimeOnly (or equivalent)
- Guid

https://github.com/ricardoboss/dart_kiota_abstractions/blob/63b687ad9d738cb4a66ab96bca90c23dda26a325/lib/src/serialization/parse_node.dart#L20

**Comment by ricardoboss** [comment]
I left out `DateOnly` and `TimeOnly` on purpose, as they don't have a Dart type to represent them intuitively and I didn't want to bloat the abstractions by implementing them myself. How do other languages deal with differences in types?

`Guid` is also not available directly in Dart, but there exists a package [`uuid`](https://pub.dev/packages/uuid) that aims to provide similar functionality. I could add those, but again, that adds more dependencies and code to manage.

**Comment by baywet** [comment]
Other languages either use native types when available or implement their own when it's not the case either directly or wrapping around a third party library. The important thing is that any existing type in use has the right license (MIT, etc...) and that it serializes/deserializes from RFC 3339 formats.

Adding more dependencies is fine to so degree for those sorts of things, as long as it's a widely adopted library (likely the application developer will already be using it) and that it's well maintained. As a safety we can come up with our own type that wraps around an external library if needs be. This way if we need to replace the implementation, it'll be transparent to consumers.

**Comment by ricardoboss** [comment]
Okay. I'd definitely prefer to create our own wrappers for a `DateOnly` and a `TimeOnly` implementation. As for `Guid`, I'd use the package I mentioned earlier as I have used it in several projects before and deem it stable enough.

**Comment by ricardoboss** [comment]
Looking for existing solutions, I found this library that could be used as a backing implementation: https://pub.dev/packages/time_machine

But as I said, I'd prefer to create our own interfaces that would wrap the packages types to guarantee we are able to replace implementations, as you said.

**Comment by ricardoboss** [comment]
I noticed the TypeScript implementation also has a `getDurationValue` method. Should I implement this as well?

https://github.com/microsoft/kiota-typescript/blob/e12b5611b9b96cdc4b1fad04cda1ca7113b0da13/packages/abstractions/src/serialization/parseNode.ts#L48

**Comment by baywet** [comment]
right, duration is for timespan/RFC 3339 durations. And yes, if it's not here today, we should also add it
