### ISSUE TITLE
consider adding a with url method in the base request builder

### ISSUE THREAD

**Issue by baywet** [ricardoboss/dart_kiota_abstractions#2]
If passing generic types and instantiating generic types from the generic type parameter is possible in Dart without using reflection this is something we might consider. It helps reducing the amount of code needed to be generated.

https://github.com/microsoft/kiota-typescript/blob/e86e70a6cc77bb58b4f5d5bac5cc6eb87dbac271/packages/abstractions/src/baseRequestBuilder.ts#L2

https://github.com/ricardoboss/dart_kiota_abstractions/blob/63b687ad9d738cb4a66ab96bca90c23dda26a325/lib/src/base_request_builder.dart#L18

**Comment by ricardoboss** [comment]
I added the signature you linked. An example usage of the interface (in Dart, there are no interfaces, only abstract classes) would look like this:

```dart
class SampleRequestBuilder extends BaseRequestBuilder<SampleRequestBuilder> {
  SampleRequestBuilder(super.requestAdapter, super.urlTemplate, super.pathParameters);

  @override
  SampleRequestBuilder withUrl(String rawUrl) {
    throw UnimplementedError();
  }
}
```

Is this what you had in mind?

**Comment by baywet** [comment]
not exactly, the goal of doing so it to avoid having to define the withUrl Method in the sample request builder. This is pseudo code, bear with me.


```dart
abstract class BaseRequestBuilder<T extends BaseRequestBuilder<T>> {
//...

  /// Returns the request builder with the provided URL.
  T withUrl(String rawUrl) {
     return new T(this.requestAdapter, this.urlTemplate, new PathParameters { "rawUrl", rawUrl });
 } 

}

class SampleRequestBuilder extends BaseRequestBuilder<SampleRequestBuilder> {
  SampleRequestBuilder(super.requestAdapter, super.urlTemplate, super.pathParameters);
}
```

**Comment by ricardoboss** [comment]
Ah, unfortunately that is not possible in Dart, as we cannot instantiate generic types. The approach normally used to do this is to pass a generator for the generic type to the function:

```dart
abstract class Foo<T extends Foo<T>> {
	T magic(T Function() generator) {
		return generator();
	}
}

class Bar extends Foo<Bar> {
}

void main() {
	final firstInstance = Bar();

	final secondInstance = firstInstance.magic(Bar.new);
}
```

This is probably not very useful. The API you suggest would mean the method is pure, no? Is there a specific reason the method needs to be pure? If not, the setter for `uri` accepts a raw uri and can be used instead.

**Comment by baywet** [comment]
Can this generator be passed in the generated constructor to the base class?
Can it accept arguments?
Otherwise that's fine, we can always generate the method, it's just an optimization

**Comment by ricardoboss** [comment]
Sure, its the equivalent of `Action<T>` or `Func<T, TResult>` in C#. `Bar.new` in the example above is something like a method group.
